name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  upload:
    name: Build & Upload Artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Build Website
      run: yarn build
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'build'

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
