name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare:
    name: Prepare Content as Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Content
        run: yarn build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build
  publish:
    name: Publish Content to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
  # deploy:
  #   name: Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: yarn
  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Build Website
  #       run: yarn build
  #     - name: Upload Artifacts
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./build
  #         user_name: github-actions[bot]
  #         user_email: 41898282+github-actions[bot]@users.noreply.github.com
